config/routes.rb
Rails.application.routes.draw do
  resources :book_authors
  resources :books
  resources :authors
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
	has_many :book_authors, :dependent => :destroy
	has_many :books, through: :book_authors
end

app/models/book.rb
class Book < ApplicationRecord
	has_many :book_authors
	has_many :authors, through: :book_authors
	
end

app/models/book_author.rb
class BookAuthor < ApplicationRecord
  belongs_to :author
  belongs_to :book
  validates_uniqueness_of :author_id, scope: :book_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
	def index
	  @authors = Author.all
	end
	def new
	  @author = Author.new
	end
	def create
		@author = Author.new(strong_params(:name, :birth_year))
		# NOTE: redirect hook here is ready for a validation,
		#		but no validation is set in the model yet.
		if @author.save
			redirect_to @author
		else
			render :new
		end
	end
	def show
	  	@author = get_instance
	end
	def edit
	  	@author = get_instance
	end
	def update
		# TODO: Add validation before (or during?) running the update.
		author = get_instance
		author.update(strong_params(:name, :birth_year))
		redirect_to author
	end
	def destroy
		get_instance.destroy
		redirect_to authors_path
	end

	private

	def strong_params(*args)
		params.require(:author).permit(*args)
	end
	def get_instance
		Author.find(params[:id])
	end

end

app/controllers/book_authors_controller.rb
class BookAuthorsController < ApplicationController
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	def index
		@books = Book.all
	end
	def show
		@book = get_instance
		# @authors = Author.all
		@authors = available_authors_to_add
	end
	def update
		book = get_instance
		# NOTE: this validation logic "works" but offers no user
		#		feedback, and also doesn't leverage the validation
		#		that exists in the model. The validation in the model
		#		works, but we are unsure how to catch that error
		#		properly in order to redirect.
		if book.authors.include?(Author.find(params[:book][:authors]))
			redirect_to book
		else
			book.authors << Author.find(params[:book][:authors])
			redirect_to book
		end
	end
	def destroy
		book = get_instance
		book.authors.delete(params[:author_id])
		redirect_to book
	end
	
	private
	
	# not using this currently
	# def strong_params(*args)
	# 	params.require(:book).permit(*args)
	# end
	def get_instance
		Book.find(params[:id])
	end
	def available_authors_to_add
		Author.all - @book.authors
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/book_authors_helper.rb
module BookAuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/authors/_form.html.erb
<%= form_for @author do |f| %>
    <li><%= f.label :name %>
    <%= f.text_field :name %></li>
    <li><%= f.label :birth_year %>			
    <%= f.number_field :birth_year %></li>
    <li><%= f.submit %></li>
<% end %>

app/views/authors/edit.html.erb
<h1>Edit Author Details</h1>

<%= render "form" %>

<%= link_to 'Undo Edits', author_path(@author) %>
<%= link_to 'Return to All Authors', authors_path %>

app/views/authors/index.html.erb
<h1>Authors</h1>
<ul>
	<% @authors.each do |author| %>
   		<li><%= link_to author.name, author_path(author) %></li>
    <% end %>
</ul>
<%= link_to 'Create New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>Create a New Author</h1>
<%= render "form" %>
<%= link_to 'Cancel Creation', authors_path %>

app/views/authors/show.html.erb
<h1>Author Details</h1>

<h2>Name: <%= @author.name %></h2>
<p>Birth Year: <%= @author.birth_year %></p>

<p>Books Written:</p>
<ul>
<% @author.books.each do |book| %>
	<li><%= link_to book.title, book_path(book) %></li>
<% end %>
</ul>

<%= button_to 'Delete Author', author_path(@author), :method => :delete %><br />

<%= link_to 'Edit Author Details', edit_author_path(@author) %><br />
<%= link_to 'Return to All Authors', authors_path %>

app/views/books/index.html.erb
<h1>Books!</h1>
<ul>
	<% @books.each do |book| %>
   		<li><%= link_to book.title, book_path(book) %></li>
    <% end %>
</ul>

app/views/books/show.html.erb
<h1><%= @book.title %></h1>
<h2>Authors:</h2>
<ul>
	<% @book.authors.each do |author| %>
		<li>
			<%= author.name %> (b. <%= author.birth_year %>)
			<%= button_to 'Remove author', {
				:controller => 'books',
				:action		=> 'destroy',
				:author_id 	=> author.id
			},
			:method => :delete %>
		</li>
	<% end %>

	<p><%= form_for @book do |f| %>
        <%= f.collection_select :authors, @authors, :id, :name %>
		<%= f.submit 'Add author to this book' %>
	<% end %></p>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails Is Fun</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav>
      <ol>
        <li>
          <a href="/authors">Authors Index</a>
        </li>
        <li>
          <a href="/books">Books Index</a>
        </li>
      </ol>
      <hr>
    </nav>

    <%= yield %>
  </body>
</html>